window.SETH_BOOKS_DATA = {
  books: [
    {id:'10-01', name_zh:'赛斯说：灵魂永生', name_en:'Seth Speaks: The Eternal Validity of the Soul', word_count:166236, sessions_count:74, sections_count:84, total_paragraphs:3944, intro_short:'赛斯体系的入口之书，集中建立灵魂、转世、死后状态和多重实相的总体框架。', intro:'赛斯体系的入口之书，集中说明灵魂、转世、死后状态、意识层级与多重实相。它适合用来建立整体宇宙观：你不是只存在于此生的肉体人格，而是更大身份在物质实相中的一个焦点。', toc:['Introduction','Chapter 1: I Do Not Have a Physical Body, Yet I Am Writing This Book','Chapter 8: Sleep, Dreams, and Consciousness','Chapter 9: The Death Experience','Chapter 12: Reincarnational Relationships','Chapter 16: Probable Systems, Men, and Gods','Chapter 22: A Goodbye and an Introduction'], core_concepts:['灵魂/存有','转世','同时性时间','多重实相','内在感官','死亡经验'], core_quotes:['你创造你自己的实相。','你现在的身份只是更大自我的一个焦点。','死亡不是终点，而是意识焦点的转换。'], reading_notes:['适合作为新读者建立整体世界观的起点。','先抓住灵魂、转世、死亡经验、多重实相几条主线。','读完后可进入《个人实相的本质》做实践连接。']},
    {id:'10-02', name_zh:'个人实相的本质', name_en:'The Nature of Personal Reality', word_count:171277, sessions_count:68, sections_count:87, total_paragraphs:3935, intro_short:'最适合实践的一本书，围绕信念、情绪、身体、健康、关系和日常经验展开。', intro:'最适合实践的一本书，围绕信念、情绪、身体、健康、金钱、关系和日常经验展开。它把“你创造自己的实相”落到可观察、可调整的心理机制。', toc:['The Living Picture of the World','Reality and Personal Beliefs','Suggestion, Telepathy, and the Grouping of Beliefs','The Body as the Living Materialization of Your Beliefs','Natural Grace, the Framework of Creativity, and the Health of Your Body','Which You? Which World?'], core_concepts:['信念','情绪','身体意识','自然罪恶感','个人实相','暗示'], core_quotes:['信念是经验的蓝图。','你认为真实的，会在你的经验中成为真实。','改变外在效果，必须改变原初信念。'], reading_notes:['适合边读边做信念觉察。','可与理宇宙中的“信念”“身体意识”“自然罪恶感”概念互读。','建议把书中练习单独整理成方法卡片。']},
    {id:'10-03', name_zh:'未知的实相：卷一', name_en:'The Unknown Reality Vol. 1', word_count:93548, sessions_count:130, sections_count:99, total_paragraphs:2048, intro_short:'进入概率、未知实相与意识结构的进阶书，把个人生命放入更大的概率系统。', intro:'进入概率、未知实相与意识结构的进阶书。它把个人生命放入更大的概率系统中，说明选择、事件、梦和身份如何在多个层面同时发生。', toc:['The Unofficial Reality','Probabilities and Alternate Focus','The Psyche and Unknown Reality','Dreams and Probable Events','Consciousness Units and Experience'], core_concepts:['概率自我','概率系统','意识单位','梦实相','事件','未知实相'], core_quotes:['每一个选择都开启经验的概率路径。','你所知的世界只是更大实相的一个可感知版本。'], reading_notes:['适合已理解基础概念后的进阶阅读。','重点关注概率、事件和梦如何连接。']},
    {id:'10-04', name_zh:'未知的实相：卷二', name_en:'The Unknown Reality Vol. 2', word_count:190045, sessions_count:262, sections_count:239, total_paragraphs:4076, intro_short:'继续展开概率、物质化、文明、语言、创造力和意识组织。', intro:'延续未知实相主题，更深入讨论概率、物质化、文明、语言、创造力和意识组织。适合在理解基本概念后继续研究。', toc:['Probabilities and Materialization','Civilizations and Collective Events','Language and Consciousness','Creativity and Psychic Organization','The Larger Psychological Structure'], core_concepts:['物质化','集体实相','创造力','心理结构','概率事件','语言'], core_quotes:['实相不是封闭系统，而是开放的创造过程。','事件有内在结构，也有外在显现。'], reading_notes:['可与卷一合读。','适合研究集体事件与文明主题。']},
    {id:'10-05', name_zh:'心灵的本质', name_en:'The Nature of the Psyche', word_count:85374, sessions_count:43, sections_count:42, total_paragraphs:1763, intro_short:'集中讨论心灵、性别、爱欲、创造性与人格深层动力。', intro:'集中讨论心灵、性别、爱欲、创造性与人格深层动力。它适合从心理和内在生命角度理解赛斯体系。', toc:['The Psyche as Open System','Sexuality and Creativity','Love, Value Fulfillment, and Personality','Inner Dynamics of Human Expression'], core_concepts:['心灵','价值完成','创造性','性别','人格','爱欲'], core_quotes:['心灵不是封闭容器，而是开放的经验场。','创造性是生命自身的基本表达。'], reading_notes:['适合与人格、创造性、性别相关概念互读。','文字相对集中，适合专题式阅读。']},
    {id:'10-06', name_zh:'个人与事件的本质', name_en:'The Individual and the Nature of Events', word_count:117981, sessions_count:141, sections_count:133, total_paragraphs:2148, intro_short:'讨论个人如何参与事件形成，连接私人经验与集体事件。', intro:'围绕个人如何参与事件形成展开，讨论私人经验与集体事件之间的连接。适合理解社会事件、历史事件和个人选择之间的关系。', toc:['The Psychology of Events','Personal and Mass Beliefs','News, Disasters, and Collective Participation','Choice and Event Formation'], core_concepts:['事件','集体信念','选择','群体意识','价值完成'], core_quotes:['事件不是偶然落到你身上，而是意识参与形成的结果。'], reading_notes:['适合理解社会事件与个人经验的关系。','可与“集体信念”“事件”概念互读。']},
    {id:'10-07', name_zh:'梦、进化与价值完成：卷一', name_en:'Dreams, Evolution, and Value Fulfillment Vol. 1', word_count:103381, sessions_count:86, sections_count:87, total_paragraphs:1717, intro_short:'从梦和进化角度解释生命发展，强调梦是现实形成的重要通道。', intro:'从梦和进化角度解释生命的发展。它把梦视为连接内在信息、物种创造力和现实行动的重要通道。', toc:['Dreams and Their Function','Evolution Reconsidered','Species Knowledge','Value Fulfillment'], core_concepts:['梦','进化','价值完成','物种意识','内在知识'], core_quotes:['梦不是逃离现实，而是现实形成的工作室。'], reading_notes:['适合关注梦和物种意识的读者。','可与梦宇宙后续内容连接。']},
    {id:'10-08', name_zh:'梦、进化与价值完成：卷二', name_en:'Dreams, Evolution, and Value Fulfillment Vol. 2', word_count:82086, sessions_count:112, sections_count:103, total_paragraphs:1560, intro_short:'继续展开梦、进化与价值完成，强调生命是意识和价值的主动表达。', intro:'继续展开梦、进化与价值完成，强调生命并非机械演化，而是意识和价值主动表达的过程。', toc:['Consciousness and Species Development','Dreams and Civilization','The Expansion of Value Fulfillment','Inner Blueprints'], core_concepts:['价值完成','梦实相','文明','意识演化','内在蓝图'], core_quotes:['生命以价值完成为方向，而不只是以生存为目标。'], reading_notes:['建议在卷一之后阅读。','适合专题研究“价值完成”。']},
    {id:'10-09', name_zh:'神奇之道', name_en:'The Magical Approach', word_count:48607, sessions_count:38, sections_count:38, total_paragraphs:1192, intro_short:'晚期温柔的一本书，强调自然流动、轻松、信任和神奇取径。', intro:'晚期非常温柔的一本书，强调自然流动、轻松、信任和“神奇取径”。适合把赛斯体系转化为生活方式。', toc:['The Magical Approach','Natural Creativity','Ease and Trust','New Ways of Solving Problems'], core_concepts:['神奇取径','自然流动','信任','创造性','轻松'], core_quotes:['神奇取径不是逃避理性，而是让更大的心智参与生活。'], reading_notes:['适合反复读，作为生活实践指南。','可与“信任”“创造性”主题连接。']},
    {id:'10-10', name_zh:'健康之道', name_en:'The Way Toward Health', word_count:136237, sessions_count:6, sections_count:21, total_paragraphs:3901, intro_short:'围绕健康、身体、疾病与疗愈展开，强调身体是有意识的合作伙伴。', intro:'围绕健康、身体、疾病与疗愈展开，强调身体是有意识、有智慧的合作伙伴。', toc:['Body Consciousness','Illness and Beliefs','Psychological Conditions for Health','Natural Healing'], core_concepts:['身体意识','健康','疾病','信念','疗愈'], core_quotes:['身体不是你的敌人，它以自己的智慧回应你的信念。'], reading_notes:['适合与《个人实相的本质》的身体章节互读。','可作为健康主题的独立入口。']},
    {id:'ES-1', name_zh:'早期课：第一册', name_en:'The Early Sessions: Book 1 of The Seth Material', word_count:149097, sessions_count:42, sections_count:42, total_paragraphs:4605},
    {id:'ES-2', name_zh:'早期课：第二册', name_en:'The Early Sessions: Book 2 of The Seth Material', word_count:148285, sessions_count:47, sections_count:47, total_paragraphs:3947},
    {id:'ES-3', name_zh:'早期课：第三册', name_en:'The Early Sessions: Book 3 of The Seth Material', word_count:152203, sessions_count:66, sections_count:66, total_paragraphs:3622},
    {id:'ES-4', name_zh:'早期课：第四册', name_en:'The Early Sessions: Book 4 of The Seth Material', word_count:148166, sessions_count:55, sections_count:55, total_paragraphs:3691},
    {id:'ES-5', name_zh:'早期课：第五册', name_en:'The Early Sessions: Book 5 of The Seth Material', word_count:146368, sessions_count:48, sections_count:48, total_paragraphs:4169},
    {id:'ES-6', name_zh:'早期课：第六册', name_en:'The Early Sessions: Book 6 of The Seth Material', word_count:138864, sessions_count:46, sections_count:46, total_paragraphs:4083},
    {id:'ES-7', name_zh:'早期课：第七册', name_en:'The Early Sessions: Book 7 of The Seth Material', word_count:139400, sessions_count:66, sections_count:65, total_paragraphs:4302},
    {id:'ES-8', name_zh:'早期课：第八册', name_en:'The Early Sessions: Book 8 of The Seth Material', word_count:147750, sessions_count:79, sections_count:78, total_paragraphs:4364},
    {id:'ES-9', name_zh:'早期课：第九册', name_en:'The Early Sessions: Book 9 of The Seth Material', word_count:190897, sessions_count:88, sections_count:87, total_paragraphs:5244}
  ],
  earlyDefaults: {
    intro_short:'早期课记录赛斯资料形成初期的大量原始材料，适合追踪体系生成过程。',
    intro:'早期课记录了赛斯资料形成初期的大量原始材料，覆盖意识、行动、人格、电性实相、梦、物质建构和内在感官等主题。它更像研究档案，适合想追踪体系生成过程的读者。',
    toc:['行动与意识的基础理论','内在感官与梦资料','人格、潜意识与自我','物质建构和电性实相','个案、练习和实验记录'],
    core_concepts:['行动','内在感官','潜意识','自我','物质建构','梦'],
    core_quotes:['意识不是静止的东西，而是行动。','物质世界是内在行动的可感知形式。','梦提供了通往内在实相的直接线索。'],
    reading_notes:['适合研究型读者。','可以按照 session 顺序阅读，也可以围绕概念专题抽读。']
  }
};
window.SETH_BOOKS_DATA.books.forEach(function(book){
  if (book.id.indexOf('ES-') === 0) {
    Object.keys(window.SETH_BOOKS_DATA.earlyDefaults).forEach(function(key){
      if (!book[key]) book[key] = window.SETH_BOOKS_DATA.earlyDefaults[key];
    });
  }
});
